export const id = '₩'
export const code = '20A9'
export const escape = parseInt(code, 16)
export const symbol = String.fromCodePoint(escape)
export const name = `Wil (${symbol}) Moore III`
export const photo = 'https://cldup.com/SU6cLiLWM0.jpg'
export const bio = '⩭⪼ I build _nifty_ web(3), api & äppz. I get your MVP or Product Demo shipped, you get funded, I walk away with ₩%! Book a Session 🤙🏾💜🌈🦄.'
export const logo = 'https://raw.githubusercontent.com/wilmoore/wonlogo.svg/main/index.png'
export const website = 'https://wilmoore.com'
export const verse = 'Proverbs 3:1-26 NLT'
export const company = 'Polyglot, LLC'
export const title = 'CTO'
export const role = 'Serial Tech Co-Founder'
export const email = 'wil.moore@wilmoore.com'
export const phone = '+1.303.944.4251'
export const address = '1317 Edgewater Dr, Suite 3326, Orlando FL 32804'
export const ref = 'James 1:5 NIV'
