export const address = '1317 Edgewater Dr, Suite 3326, Orlando FL 32804'
export const bio = 'Technical Accountability Partner for Startup Founders (Mentorship Available)! 🤙🏾💜🌈🦄.'
export const book_a_session = '//calendly.com/wilmoore'
export const code = '20A9'
export const company = 'Polyglot, LLC'
export const email = 'wil.moore@wilmoore.com'
export const escape = parseInt(code, 16)
export const id = String.fromCodePoint(escape)
export const logo = '//raw.githubusercontent.com/wilmoore/wonlogo.svg/main/index.png'
export const name = `Wil (${id}) Moore III`
export const phone = '+1.303.944.4251'
export const photo = '//cldup.com/SU6cLiLWM0.jpg'
export const ref = ['Genesis 2:1-3 NLT', '1 Peter 4:10 NLT']
export const role = 'CTO'
export const symbol = String.fromCodePoint(escape)
export const title = 'Tech Mentor'
export const website = '//wilmoore.com'
